title: 拾陆
description: Keep

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jsonzhang
   twitter: jsonzhang
   facebook: jsonzhang
   email: jsonzhang@icloud.com

google_analytics: "UA-58263416-1"


# Build settings
markdown: kramdown