title: Dion
description: keep

url: http://jsonzhang.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
google_analytics: "false"
imgArray: ["1.jpg"]

markdown: kramdown
highlighter: rouge
paginate: 5

gems: ["jekyll-paginate"]

navigation:
 # - title: Home
   # url: /index.html
 # - title: About
   # url: /about

social:
   github: jsonzhang
   twitter: jsonzhang
   facebook: jsonzhang
   email: jsonzhang@icloud.com

google_analytics: "UA-58263416-1"


exclude: ["node_modules", "gulpfile.js", "package.json","assets/scss"]