# Site settings
title: 拾陆
email: jsonzhang@icloud.com
description: keep changing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jsonzhang.com" # the base hostname & protocol for your site
twitter_username: jsonzhang
github_username:  jsonzhang

# Build settings
markdown: kramdown
